<a href="https://colab.research.google.com/github/Syed-Tashfeen/PYTHON-for-AI-ML/blob/main/numpyFinal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
A={2:"Tashfeen"}
print(A)
print(A[2])

{2: 'Tashfeen'}
Tashfeen


In [ ]:
A=['TASHFEEN','MAWIYA','TAMEEM']
print(A[1])


MAWIYA


In [ ]:
A={1,2,2,3,5,'@','MAWIYA'}
print(A)


{1, 2, 3, 5, '@', 'MAWIYA'}


In [ ]:
import numpy as np
list=[1,2,3,4]
np.array(list)



array([1, 2, 3, 4])

In [ ]:
list=[1,2,3,4]
arr=np.array(list)
type(arr)

numpy.ndarray

In [ ]:
arr.shape
#1D array as it contanins only rows (rows,column)

(4,)

In [ ]:
#MULTIDIMENTIONAL NUMPY ARRAY
list1=[1,2,3,4,5]
list2=[2,3,4,5,6]
list3=[3,4,5,6,7]
np.array([list1,list2,list3])


array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [ ]:
arr1=np.array([list1,list2,list3])
arr1.shape


(3, 5)

In [ ]:
#INDEXING
arr # array([1, 2, 3, 4])
arr[2] #np.int64(3)
print(arr[2]) #3
arr[:] #array([1, 2, 3, 4])
arr[::] #array([1, 2, 3, 4]) [::jump size]
arr[::-1] #array([4, 3, 2, 1])
arr[::-2]#array([4, 2])

3


array([4, 2])

In [ ]:
#FOR MULTIDIMINTIONAL ARRAY
#arr1[whole row:,column]
arr1 #array([[1, 2, 3, 4, 5],
       #[2, 3, 4, 5, 6],
       #[3, 4, 5, 6, 7]])
arr1[:,1] #array([2, 3, 4])
arr1[1:,1:3] #array([[3, 4],
      # [4, 5]])
arr1[:,3:] #array([[4, 5],
      # [5, 6],
       #[6, 7]])
arr1[:,3:].shape #(3, 2)




array([[4, 5],
       [5, 6],
       [6, 7]])

In [ ]:
#EDA(Expodetrary Data Analysis)
arr #array([1, 2, 3, 4])
arr<2#array([ True, False, False, False]
arr[arr<2]#arr[arr<2]
arr1.shape#(3, 5)
arr1 #array([[1, 2, 3, 4, 5],
       #[2, 3, 4, 5, 6],
       #[3, 4, 5, 6, 7]])
arr1.reshape(5,3) #array([[1, 2, 3],
                          # [4, 5, 2],
                          # [3, 4, 5],
                          # [6, 3, 4],
                          # [5, 6, 7]])



array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 3, 4],
       [5, 6, 7]])

In [ ]:
arr #array([1, 2, 3, 4])
arr*arr #array([ 1,  4,  9, 16])
arr*2 #array([2, 4, 6, 8])
arr1*2 #array([[ 2,  4,  6,  8, 10],
       #[ 4,  6,  8, 10, 12],
       #[ 6,  8, 10, 12, 14]])
arr1*arr1 #array([[ 1,  4,  9, 16, 25],
       #[ 4,  9, 16, 25, 36],
       #[ 9, 16, 25, 36, 49]])
np.ones((5,3))#returns 1 in the array of rows and coumn #array([[1., 1., 1.],
                    # [1., 1., 1.],
                    # [1., 1., 1.],
                    #[1., 1., 1.],
                    #[1., 1., 1.]])
np.zeros((3,2))#return zero in the array array([[0., 0.],
                                              #[0., 0.],
                                              #[0.,0.]])
np.random.randint(10,50)#return random no everytime between
#np.random.randint(10,50,size of an array)
np.random.randint(10,50,4)#array([26, 27, 44, 23])
np.random.randint(10,50,4).reshape(2,2)#array([[43, 32],
      #                                          [19, 31]])
np.random.randn(5,6)#array([[ 1.41816784, -1.06672301, -0.72421846, -0.36538459, -1.45924584,
      #  -0.24843318],
      # [ 0.50563457, -0.36371545,  0.93203926, -1.35166024,  0.12633889,
      #  -0.19052763],
      # [ 0.85991257,  2.36073171,  0.56756863,  0.43021323,  0.04728913,
      #  -1.56804201],
      # [ 0.81318347, -0.07954573, -0.6492227 ,  0.07249082,  0.25713302,
      #  -1.60056143],
     #  [ 1.25893127,  0.48897539, -0.88964918,  0.77369556,  1.3474557 ,
      #  -0.22667937]])
np.random.random_sample((4,7))#array([[0.51795297, 0.44208825, 0.21454708, 0.30735082, 0.37210471,
       # 0.52300005, 0.57381892],
       #[0.46366101, 0.73988228, 0.28194817, 0.6723564 , 0.90799403,
       # 0.44197393, 0.70396301],
      # [0.52957146, 0.27766806, 0.61010513, 0.72642438, 0.69145797,
      #  0.28336332, 0.39133407],
      # [0.14308364, 0.11216522, 0.89514276, 0.59046933, 0.2773425 ,
      #  0.60600443, 0.40485346]])


array([[0.51795297, 0.44208825, 0.21454708, 0.30735082, 0.37210471,
        0.52300005, 0.57381892],
       [0.46366101, 0.73988228, 0.28194817, 0.6723564 , 0.90799403,
        0.44197393, 0.70396301],
       [0.52957146, 0.27766806, 0.61010513, 0.72642438, 0.69145797,
        0.28336332, 0.39133407],
       [0.14308364, 0.11216522, 0.89514276, 0.59046933, 0.2773425 ,
        0.60600443, 0.40485346]])